apiVersion: v1
kind: Service
metadata:
  name: {{ include "agola.fullname" . }}-gitserver-headless
  labels:
    {{- include "agola.labels" . | nindent 4 }}
    agola.io/component: gitserver
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: gitserver
      port: 4003
      targetPort: 4003
  selector:
    {{- include "agola.selectorLabels" . | nindent 4 }}
    agola.io/component: gitserver
