apiVersion: v1
kind: Service
metadata:
  name: {{ include "agola.fullname" . }}-gitserver
  labels:
    {{- include "agola.labels" . | nindent 4 }}
    agola.io/component: gitserver
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: gitserver
      port: {{ .Values.gitserver.service.port }}
      targetPort: 4003
  selector:
    {{- include "agola.selectorLabels" . | nindent 4 }}
    agola.io/component: gitserver
