apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "agola.fullname" . }}-configstore
  {{- with .Values.configstore.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "agola.labels" . | nindent 4 }}
    agola.io/component: configstore
    {{- with .Values.configstore.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  revisionHistoryLimit: {{ .Values.configstore.deployment.revisionHistoryLimit }}
  replicas: {{ .Values.configstore.deployment.replicas }}
  strategy:
    {{- toYaml .Values.configstore.updateStrategy | nindent 4 }}
  selector:
    matchLabels:
      {{- include "agola.selectorLabels" . | nindent 6 }}
      agola.io/component: configstore
  template:
    metadata:
      {{- with .Values.configstore.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "agola.selectorLabels" . | nindent 8 }}
        agola.io/component: configstore
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "agola.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.configstore.podSecurityContext | nindent 8 }}
      containers:
        - name: configstore
          securityContext:
            {{- toYaml .Values.configstore.securityContext | nindent 12 }}
          image: "{{ .Values.image.registry }}/{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /bin/agola
            - serve
            - "--config"
            - /etc/agola/config.yml
            - "--components"
            - configstore
          ports:
            - name: configstore
              containerPort: 4002
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 4002
          resources:
            {{- toYaml .Values.configstore.resources | nindent 12 }}
          volumeMounts:
          - name: conf
            mountPath: /etc/agola
          - name: local
            mountPath: {{ .Values.config.localBaseDir }}
      {{- with .Values.configstore.extraContainers }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configstore.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configstore.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configstore.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configstore.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.configstore.dnsConfig }}
      dnsConfig:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: conf
          secret:
            secretName: {{ include "agola.fullname" . }}-conf
        - name: local
          emptyDir: {}
      {{- with .Values.configstore.extraVolumes }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
