apiVersion: v1
kind: Service
metadata:
  name: {{ include "agola.fullname" . }}-configstore
  labels:
    {{- include "agola.labels" . | nindent 4 }}
    agola.io/component: configstore
spec:
  type: {{ .Values.configstore.service.type }}
  ports:
    - protocol: TCP
      name: configstore
      port: {{ .Values.configstore.service.port }}
      targetPort: 4002
  selector:
    {{- include "agola.selectorLabels" . | nindent 4 }}
    agola.io/component: configstore
