apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agola.fullname" . }}-conf
  {{- with .Values.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    {{- include "agola.labels" . | nindent 4 }}
    {{- with .Values.config.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- with .Values.config.file }}
stringData:
  config.yml: |
    {{- toYaml . | nindent 4 }}
    {{- end }}
