apiVersion: v1
kind: Service
metadata:
  name: {{ include "agola.fullname" . }}-runservice
  labels:
    {{- include "agola.labels" . | nindent 4 }}
    agola.io/component: runservice
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      name: runservice
      port: {{ .Values.runservice.service.port }}
      targetPort: 4000
  selector:
    {{- include "agola.selectorLabels" . | nindent 4 }}
    agola.io/component: runservice
